-- Create proposals table
-- This table stores governance proposals with Theory of Change structure
CREATE TABLE IF NOT EXISTS public.proposals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    objectives JSONB NOT NULL, -- Stores complete Theory of Change structure: array of objectives, each with preconditions, indicative steps, and key indicators
    functionalities TEXT NOT NULL,
    discussion TEXT NOT NULL,
    voting_period_id TEXT NOT NULL,
    user_id UUID REFERENCES auth.users(id),
    CONSTRAINT proposals_title_check CHECK (char_length(title) > 0),
    CONSTRAINT proposals_functionalities_check CHECK (char_length(functionalities) > 0),
    CONSTRAINT proposals_discussion_check CHECK (char_length(discussion) > 0),
    CONSTRAINT proposals_objectives_check CHECK (
        jsonb_typeof(objectives) = 'array' AND
        jsonb_array_length(objectives) >= 2
    )
);

-- Add indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_proposals_voting_period ON public.proposals(voting_period_id);
CREATE INDEX IF NOT EXISTS idx_proposals_created_at ON public.proposals(created_at DESC);

-- Enable Row Level Security
ALTER TABLE public.proposals ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Policy: Anyone can read proposals
CREATE POLICY "Anyone can read proposals"
ON public.proposals
FOR SELECT
USING (true);

-- Policy: Authenticated users can create proposals
CREATE POLICY "Authenticated users can create proposals"
ON public.proposals
FOR INSERT
TO authenticated
WITH CHECK (true);

-- Policy: Users can update their own proposals
CREATE POLICY "Users can update their own proposals"
ON public.proposals
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own proposals
CREATE POLICY "Users can delete their own proposals"
ON public.proposals
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

